version: '3.5'

services:
  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=rhombus_ai
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rhombus_ai
    ports:
      - "5432"
    volumes:
      - dbdata:/var/lib/postgresql/data:delegated

  db_nosql:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db:delegated

  # TODO add script to init the bucket with public permission to easy local setup
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=bucket

  broker:
    image: "rabbitmq:alpine"

  result:
    image: "redis:alpine"
    ports:
    - "6379:6379"

  frontend:
    build:
      dockerfile: frontend/Dockerfile
      context: .
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"

  backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/user/app/
    env_file: backend/.env
    depends_on:
      - db
      - db_nosql
      - minio
      - broker
      - result
      - frontend

  celery:
    build:
      dockerfile: backend/Dockerfile
      context: .
    command: celery --app=myproject worker --loglevel=info
    volumes:
      - ./:/home/user/app/
    env_file: backend/.env
    depends_on:
      - db
      - broker
      - result

  mailhog: # service for faking a SMTP server
    image: mailhog/mailhog
    ports:
      - '1025:1025' # smtp server
      - '8025:8025' # web ui

volumes:
  dbdata:
    name: rhombus_ai_dbdata
    external: true
  mongodata:
    name: rhombus_ai_dbdata_nosql
    external: true
  minio_data:
